/**
 * @import {
 *   ExportDefaultDeclaration,
 *   JSXClosingElement,
 *   JSXOpeningElement,
 *   Node,
 *   Program
 * } from 'estree-jsx'
 * @import { Scope } from 'estree-util-scope'
 * @import { Nodes } from 'mdast'
 * @import { MdxjsEsm } from 'mdast-util-mdxjs-esm'
 * @import { MappedOutput, SpanMapping, TransformParams, TransformResult } from '../protocol.js'
 * @import { Project } from '../util/projects.js'
 */

import '../plugins/register.js'

import { createVisitors } from 'estree-util-scope'
import { walk } from 'estree-walker'

import { jsxIndent } from '../util/constants.js'
import { isInjectableComponent, isInjectableEstree } from '../util/jsx.js'
import { addOffset, mapMarkdownToJsx, padOffsets } from '../util/mapping.js'
import {
  getListItemMarkerLength,
  getNodeEndOffset,
  getNodeStartOffset,
  processCodeBlock,
  visit
} from '../util/mdast.js'
import { nonNull, resolveProviderImportSource } from '../util/misc.js'
import { getNextPropsType } from '../util/next.js'
import { projects } from '../util/projects.js'
import { getReactRouterPropsType } from '../util/react-router.js'
import { toDiagnostic } from '../util/vfile.js'

/**
 * Render the content that should be prefixed to the embedded JavaScript file.
 *
 * @param {string} jsxImportSource
 *   The string to use for the JSX import source tag.
 */
const jsPrefix = (jsxImportSource) => `/* @jsxRuntime automatic */
/** @import { JSX } from '${jsxImportSource}/jsx-runtime' */

import { Fragment as _Fragment } from '${jsxImportSource}/jsx-runtime'
`

/**
 * @param {string} propsName
 */
const layoutJsDoc = (propsName) => `
/** @typedef {MDXContentProps & { children: JSX.Element }} MDXLayoutProps */

/**
 * There is one special component: [MDX layout](https://mdxjs.com/docs/using-mdx/#layout).
 * If it is defined, it’s used to wrap all content.
 * A layout can be defined from within MDX using a default export.
 *
 * @param {{readonly [K in keyof MDXLayoutProps]: MDXLayoutProps[K]}} ${propsName}
 *   The [props](https://mdxjs.com/docs/using-mdx/#props) that have been passed to the MDX component.
 *   In addition, the MDX layout receives the \`children\` prop, which contains the rendered MDX content.
 */`

/**
 * @param {boolean} isAsync
 *   Whether or not the `_createMdxContent` should be async
 * @param {Scope} [scope]
 * @param {boolean} [hasImportSource]
 */
const createMdxContentStart = (isAsync, scope, hasImportSource) => `
/**
 * @internal
 *   **Do not use.** This function is generated by MDX for internal use.
 *
 * @param {{readonly [K in keyof MDXContentProps]: MDXContentProps[K]}} props
 *   The [props](https://mdxjs.com/docs/using-mdx/#props) that have been passed to the MDX component.
 * @returns {${isAsync ? 'Promise<JSX.Element>' : 'JSX.Element'}}
 *   A JSX element which represents the MDX content.
 */
${isAsync ? 'async ' : ''}function _createMdxContent(props) {
  /**
   * @internal
   *   **Do not use.** This variable is generated by MDX for internal use.
   */
  const _components = {
    ...(/** @type {{[K in keyof JSX.IntrinsicElements]: K}} */ ({})),${hasImportSource ? '\n    ..._provideComponents(),' : ''}
    ...props.components,
    /** The [props](https://mdxjs.com/docs/using-mdx/#props) that have been passed to the MDX component. */
    props${
      scope?.defined.map((name) => `,\n    /** {@link ${name}} */\n    ${name}`).join('') ?? ''
    }
  }
  _components
  return <_Fragment>`

const createMdxContentEnd = `
  </_Fragment>
}
`

const mdxContentStart = `
/**
 * Render the MDX contents.
 *
 * @param {{readonly [K in keyof MDXContentProps]: MDXContentProps[K]}} props
 *   The [props](https://mdxjs.com/docs/using-mdx/#props) that have been passed to the MDX component.
 * @returns {JSX.Element}
 *   A JSX element which represents the MDX content.
 */
export default function MDXContent(props) {
  return `

/**
 * @param {string} [propsType]
 */
const mdxContentEnd = (propsType = 'Props') => `
}

// @ts-ignore
/** @typedef {(void extends ${propsType} ? {} : ${propsType}) & {components?: {}}} MDXContentProps */
`

/**
 * A fallback to use if generating mapped content fails.
 *
 * @param {string} jsxImportSource
 *   The string to use for the JSX import source tag.
 */
const fallback = (jsxImportSource) =>
  jsPrefix(jsxImportSource) +
  createMdxContentStart(false) +
  createMdxContentEnd +
  mdxContentStart +
  mdxContentEnd()

/**
 * @param {ExportDefaultDeclaration} node
 * @returns {string | undefined}
 */
function getPropsName(node) {
  const { declaration } = node
  const { type } = declaration

  if (
    type !== 'ArrowFunctionExpression' &&
    type !== 'FunctionDeclaration' &&
    type !== 'FunctionExpression'
  ) {
    return
  }

  if (declaration.params.length === 1) {
    const parameter = declaration.params[0]
    if (parameter.type === 'Identifier') {
      return parameter.name
    }
  }

  return 'props'
}

/** @type {Partial<Record<Nodes["type"], string>>} */
const mdastElementNodeNameMap = {
  blockquote: 'blockquote',
  html: 'html',
  image: 'img',
  imageReference: 'img',
  link: 'a',
  linkReference: 'a',
  listItem: 'li',
  paragraph: 'p',
  table: 'table',
  tableCell: 'td',
  tableRow: 'tr'
}

/**
 * Get the JSX node names for a given AST node.
 *
 * @param {Nodes} node
 * @returns {string}
 */
function getJsxNodeNameForMdast(node) {
  if (node.type === 'heading') {
    return `h${node.depth}`
  }

  if (node.type === 'list') {
    return node.ordered ? 'ol' : 'ul'
  }

  if (mdastElementNodeNameMap[node.type]) {
    return /** @type string */ (mdastElementNodeNameMap[node.type])
  }

  // JSX Fragment
  return ''
}

/**
 * @param {TransformParams} params
 * @param {Project} project
 * @returns {TransformResult}
 */
export function transformActual(params, project) {
  const { content: mdx, fileName } = params
  const {
    checkCodeBlocks,
    checkMdx,
    configFileName,
    jsxImportSource,
    parse,
    plugins,
    preset,
    providerImportSource
  } = project
  const ast = parse(params)
  const resolvedProviderImportSource = resolveProviderImportSource(
    fileName,
    configFileName,
    providerImportSource
  )

  let hasAwait = false
  let esm = checkMdx ? '// @ts-check\n' : ''
  let jsx = ''
  let jsxVariables = ''

  /** @type {string | undefined} */
  let propsType
  if (configFileName) {
    switch (preset) {
      case '@react-router/fs-routes': {
        const routerFields = getReactRouterPropsType(configFileName, fileName)
        if (routerFields) {
          propsType = routerFields.type
          esm += routerFields.import
        }
        break
      }
      case 'next':
        propsType = getNextPropsType(configFileName, fileName)
        break
    }
  }

  /** @type {Node | undefined} */
  let layoutNode

  /** @type {MappedOutput[] | undefined} */
  let supplemental

  /**
   * The Volar mapping that maps all ESM syntax of the MDX file to the virtual JavaScript file.
   *
   * @type {SpanMapping[]}
   */
  const esmMappings = []

  /**
   * The Volar mapping that maps all JSX syntax of the MDX file to the virtual JavaScript file.
   *
   * @type {SpanMapping[]}
   */
  const jsxMappings = []

  /**
   * @type {SpanMapping[]}
   */
  const jsxVariablesMapping = []

  const visitors = createVisitors()

  for (const child of ast.children) {
    if (child.type !== 'mdxjsEsm') {
      continue
    }

    const estree = child.data?.estree

    if (estree) {
      walk(estree, {
        enter(node) {
          visitors.enter(node)

          if (
            node.type === 'ArrowFunctionExpression' ||
            node.type === 'FunctionDeclaration' ||
            node.type === 'FunctionExpression'
          ) {
            this.skip()
            visitors.exit(node)
          }
        },
        leave: visitors.exit
      })
    }
  }

  const programScope = visitors.scopes[0]

  esm += jsPrefix(jsxImportSource)
  if (resolvedProviderImportSource) {
    esm += `import { useMDXComponents as _provideComponents } from ${JSON.stringify(resolvedProviderImportSource)}\n`
  }

  /**
   * Process exports of an MDX ESM node.
   *
   * @param {MdxjsEsm} node
   *   The MDX ESM node to process.
   * @returns {undefined}
   */
  function processExports(node) {
    const start = node.position?.start?.offset
    const end = node.position?.end?.offset

    if (start === undefined || end === undefined) {
      return
    }

    const body = node.data?.estree?.body

    if (!body?.length) {
      esm = addOffset(esmMappings, mdx, esm, start, end, true)
      return
    }

    bodyLoop: for (const child of body) {
      if (child.type === 'ExportDefaultDeclaration') {
        const propsName = getPropsName(child)
        layoutNode = child
        if (propsName) {
          esm += layoutJsDoc(propsName)
        }

        esm += '\nconst MDXLayout = '
        esm = addOffset(esmMappings, mdx, esm, child.declaration.start, child.end, true)
        continue
      }

      if (child.type === 'ExportNamedDeclaration' && child.source) {
        const { specifiers } = child
        for (let index = 0; index < specifiers.length; index += 1) {
          const specifier = specifiers[index]
          if (
            specifier.local.type === 'Identifier'
              ? specifier.local.name === 'default'
              : specifier.local.value === 'default'
          ) {
            layoutNode = specifier
            esm = addOffset(esmMappings, mdx, esm, start, specifier.start)
            const nextPosition =
              index === specifiers.length - 1 ? specifier.end : mdx.indexOf(',', specifier.end) + 1
            esm = addOffset(esmMappings, mdx, esm, nextPosition, end, true)
            esm += '\nimport {'
            esm +=
              specifier.exported.type === 'Identifier'
                ? specifier.exported.name
                : JSON.stringify(specifier.exported.value)
            esm += ' as MDXLayout} from '
            const sourceLength = child.source.end - child.source.start
            esmMappings.unshift([esm.length, sourceLength, child.source.start, sourceLength, 0, 0])
            esm += child.source.raw
            continue bodyLoop
          }
        }
      }

      esm = addOffset(esmMappings, mdx, esm, child.start, child.end, true)
    }

    esm += '\n'
    esmMappings.push([esm.length, 1, end, 1, 2, 0])
    esm += ';\n'
  }

  /**
   * @param {Program} program
   * @param {number} lastIndex
   * @returns {number}
   */
  function processJsxExpression(program, lastIndex) {
    /** @type {Map<Node, Scope | undefined>} */
    const localScopes = new Map()

    /** @type {Map<Node, Node | null>} */
    const parents = new Map()
    let newIndex = lastIndex
    let functionNesting = 0

    /**
     * @param {JSXClosingElement | JSXOpeningElement} node
     * @returns {undefined}
     */
    function processJsxTag(node) {
      const { name } = node

      if (name.type !== 'JSXIdentifier') {
        return
      }

      if (!isInjectableEstree(name, localScopes, parents)) {
        return
      }

      jsx = addOffset(jsxMappings, mdx, jsx, newIndex, name.start)
      jsx += '_components.'
      if (node.name && node.type === 'JSXOpeningElement') {
        jsxVariables += '// @ts-ignore\n'
        jsxVariables = addOffset(jsxVariablesMapping, mdx, jsxVariables, name.start, name.end)
        jsxVariables += '\n'
      }

      newIndex = name.start
    }

    walk(program, {
      enter(node, parent) {
        if (node.type === 'Program') {
          return
        }

        visitors.enter(node)
        localScopes.set(node, visitors.scopes.at(-1))
        parents.set(node, parent)
      },
      leave(node) {
        if (node.type === 'Program') {
          return
        }

        visitors.exit(node)
      }
    })

    walk(program, {
      enter(node) {
        switch (node.type) {
          case 'JSXElement':
            processJsxTag(node.openingElement)
            break

          case 'ArrowFunctionExpression':
          case 'FunctionDeclaration':
          case 'FunctionExpression':
            functionNesting += 1
            break

          case 'AwaitExpression':
            if (!functionNesting) {
              hasAwait = true
            }

            break

          case 'ForOfStatement':
            if (!functionNesting) {
              hasAwait ||= node.await
            }

            break

          default:
        }
      },

      leave(node) {
        switch (node.type) {
          case 'ArrowFunctionExpression':
          case 'FunctionDeclaration':
          case 'FunctionExpression':
            functionNesting -= 1
            break

          case 'JSXElement': {
            const { closingElement } = node

            if (closingElement) {
              processJsxTag(closingElement)
            }

            break
          }

          default:
        }
      }
    })

    return newIndex
  }

  visit(
    ast,
    (node) => {
      const start = node.position?.start?.offset
      let end = node.position?.end?.offset

      if (start === undefined || end === undefined) {
        return
      }

      for (const plugin of plugins) {
        plugin.visit?.(node)
      }

      switch (node.type) {
        case 'break':
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'br', start, end - start, 'self')
          break

        case 'code':
          jsx += jsxIndent
          jsx += '<pre>'
          jsx += jsxIndent
          jsx += '<code>'
          if (checkCodeBlocks) {
            const output = processCodeBlock(node, mdx)
            if (output) {
              supplemental ||= []
              supplemental.push(output)
            }
          }
          break

        case 'delete': {
          const length = mdx.charAt(start + 1) === '~' ? 2 : 1
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'del', start, length)
          break
        }

        case 'emphasis':
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'em', start, 1)
          break

        case 'heading': {
          const { depth } = node
          let originalStart
          let length
          if (mdx.charAt(start) === '#') {
            // ATX heading
            originalStart = start
            length = depth
          } else {
            // Setext heading
            originalStart = end
            const underlineChar = mdx.charAt(end - 1)
            while (mdx.charAt(originalStart - 1) === underlineChar) {
              originalStart -= 1
            }
            length = end - originalStart
          }
          jsx = mapMarkdownToJsx(jsxMappings, jsx, `h${depth}`, originalStart, length)
          break
        }

        case 'inlineCode': {
          let length = 1
          while (mdx.charAt(start + length) === '`') {
            length += 1
          }
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'code', start, length)
          break
        }

        case 'listItem': {
          const length = getListItemMarkerLength(node, mdx)
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'li', getNodeStartOffset(node), length)
          break
        }

        case 'mdxjsEsm':
          processExports(node)
          break

        case 'mdxJsxFlowElement':
        case 'mdxJsxTextElement': {
          if (node.children.length > 0) {
            end = mdx.lastIndexOf('>', getNodeStartOffset(node.children[0]) - 1) + 1
          }

          let lastIndex = start + 1
          jsx = addOffset(jsxMappings, mdx, jsx + jsxIndent, start, lastIndex)
          if (isInjectableComponent(node.name, programScope)) {
            jsx += '_components.'
            if (node.name) {
              jsxVariables += '// @ts-ignore\n'
              jsxVariables = addOffset(
                jsxVariablesMapping,
                mdx,
                jsxVariables,
                lastIndex,
                lastIndex + node.name.length
              )
              jsxVariables += '\n'
            }
          }

          if (node.name) {
            jsx = addOffset(jsxMappings, mdx, jsx, lastIndex, lastIndex + node.name.length)
            lastIndex += node.name.length
          }

          for (const attribute of node.attributes) {
            if (typeof attribute.value !== 'object') {
              continue
            }

            const program = attribute.value?.data?.estree

            if (program) {
              lastIndex = processJsxExpression(program, lastIndex)
            }
          }

          jsx = addOffset(jsxMappings, mdx, jsx, lastIndex, end)
          break
        }

        case 'mdxFlowExpression':
        case 'mdxTextExpression': {
          const program = node.data?.estree
          jsx += jsxIndent

          if (program?.body.length) {
            const newIndex = processJsxExpression(program, start)
            jsx = addOffset(jsxMappings, mdx, jsx, newIndex, end)
          } else {
            jsx = addOffset(jsxMappings, mdx, jsx, start, start + 1)
            jsx = addOffset(jsxMappings, mdx, jsx, end - 1, end)
            esm = addOffset(esmMappings, mdx, esm, start + 1, end - 1)
            esm += '\n'
          }

          break
        }

        case 'root':
        case 'toml':
        case 'yaml':
          break

        case 'strong':
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'strong', start, 2)
          break

        case 'text':
          jsx += jsxIndent
          jsx += "{''}"
          break

        case 'thematicBreak':
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'hr', start, end - start, 'self')
          break

        default:
          jsx += jsxIndent
          jsx += '<'
          jsx += getJsxNodeNameForMdast(node)
          jsx += '>'
          break
      }
    },
    (node) => {
      switch (node.type) {
        case 'break':
        case 'mdxTextExpression':
        case 'mdxjsEsm':
        case 'mdxFlowExpression':
        case 'root':
        case 'text':
        case 'thematicBreak':
        case 'toml':
        case 'yaml':
          break

        case 'code':
          jsx += jsxIndent
          jsx += '</code>'
          jsx += jsxIndent
          jsx += '</pre>'
          break

        case 'delete': {
          const end = getNodeEndOffset(node)
          const length = mdx.charAt(end - 2) === '~' ? 2 : 1
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'del', end - length, length, true)
          break
        }

        case 'emphasis':
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'em', getNodeEndOffset(node) - 1, 1, true)
          break

        case 'heading':
          jsx += jsxIndent
          jsx += '{/* @ts-ignore */}'
          jsx += jsxIndent
          jsx += `</_components.h${node.depth}>`
          break

        case 'inlineCode': {
          const end = getNodeEndOffset(node)
          let length = 1
          while (mdx.charAt(end - length - 1) === '`') {
            length += 1
          }
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'code', end - length, length, true)
          break
        }

        case 'listItem': {
          const length = getListItemMarkerLength(node, mdx)
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'li', getNodeStartOffset(node), length, true)
          break
        }

        case 'mdxJsxFlowElement':
        case 'mdxJsxTextElement': {
          const child = node.children?.at(-1)

          if (child) {
            const start = mdx.indexOf('<', getNodeEndOffset(child) - 1)
            const end = getNodeEndOffset(node)

            if (isInjectableComponent(node.name, programScope)) {
              const closingStart = start + 2
              jsx = addOffset(jsxMappings, mdx, jsx + jsxIndent, start, closingStart)
              jsx += '_components.'
              jsx = addOffset(jsxMappings, mdx, jsx, closingStart, end)
            } else {
              jsx = addOffset(jsxMappings, mdx, jsx + jsxIndent, start, end)
            }
          }

          break
        }

        case 'strong':
          jsx = mapMarkdownToJsx(jsxMappings, jsx, 'strong', getNodeEndOffset(node) - 2, 2, true)
          break

        default:
          jsx += jsxIndent
          jsx += '</'
          jsx += getJsxNodeNameForMdast(node)
          jsx += '>'
          break
      }
    }
  )

  for (const plugin of plugins) {
    esm += '\n'
    const [pluginCode, pluginMappings] = plugin.finalize()
    padOffsets(pluginMappings, esm.length)
    esmMappings.push(...pluginMappings)
    esm += pluginCode
    esm += '\n'
  }

  esm += createMdxContentStart(hasAwait, programScope, Boolean(resolvedProviderImportSource))

  padOffsets(jsxMappings, esm.length)
  esm += jsx + createMdxContentEnd + mdxContentStart
  esm += '<'
  if (layoutNode) {
    esmMappings.push([esm.length, 9, layoutNode.start, layoutNode.end - layoutNode.start, 1, 0])
    esm += 'MDXLayout {...props}'
  } else {
    esm += '_Fragment'
  }
  esm += '>\n'
  esm += '    <_createMdxContent {...props} />\n'
  esm += `  </${layoutNode ? 'MDXLayout' : '_Fragment'}>`
  esm += mdxContentEnd(propsType)

  padOffsets(jsxVariablesMapping, esm.length)
  esm += jsxVariables

  return {
    text: esm,
    extension: '.jsx',
    mappings: [...esmMappings, ...jsxMappings, ...jsxVariablesMapping],
    supplemental
  }
}

/**
 * Transform MDX content into mapped TypeScript content.
 *
 * @param {TransformParams} params
 *   The transform parameters as sent by TypeScript.
 * @returns {TransformResult}
 *   The transform result that TypeScript expects.
 */
export function transform(params) {
  const project = nonNull(projects.get(params.projectHandle))

  try {
    return transformActual(params, project)
  } catch (error) {
    return {
      diagnostics: [toDiagnostic(error)],
      mappings: [],
      extension: '.jsx',
      text: fallback(project.jsxImportSource)
    }
  }
}
