/**
 * @import {
 * ExportDefaultDeclaration,
 * JSXClosingElement,
 * JSXOpeningElement,
 * Node,
 * Program
 * } from 'estree-jsx'
 * @import { Scope } from 'estree-util-scope'
 * @import { Nodes, Root } from 'mdast'
 * @import { MdxjsEsm } from 'mdast-util-mdxjs-esm'
 * @import { MappedOutput, SpanMapping, TransformParams, TransformResult } from '../protocol.js'
 * @import { VirtualCodePluginObject } from '../util/plugin.js'
 */

import '../plugins/register.js'

import { createVisitors } from 'estree-util-scope'
import { walk } from 'estree-walker'
import remarkMdx from 'remark-mdx'
import remarkParse from 'remark-parse'
import { unified } from 'unified'

import { isInjectableComponent, isInjectableEstree } from '../util/jsx.js'
import { addOffset, padOffsets } from '../util/mapping.js'
import { getMarkdownExtensions } from '../util/markdown.js'
import { getNodeEndOffset, getNodeStartOffset, processCodeBlock, visit } from '../util/mdast.js'
import { hasExtension, resolveProviderImportSource } from '../util/misc.js'
import { resolvePlugins } from '../util/plugin.js'
import { projects } from '../util/projects.js'
import { toDiagnostic } from '../util/vfile.js'

/**
 * Render the content that should be prefixed to the embedded JavaScript file.
 *
 * @param {string} jsxImportSource
 *   The string to use for the JSX import source tag.
 */
const jsPrefix = (jsxImportSource) => `/* @jsxRuntime automatic */
/** @import { JSX } from '${jsxImportSource}/jsx-runtime' */

import { Fragment as _Fragment } from '${jsxImportSource}/jsx-runtime'
`

/**
 * @param {string} propsName
 */
const layoutJsDoc = (propsName) => `
/** @typedef {MDXContentProps & { children: JSX.Element }} MDXLayoutProps */

/**
 * There is one special component: [MDX layout](https://mdxjs.com/docs/using-mdx/#layout).
 * If it is defined, it’s used to wrap all content.
 * A layout can be defined from within MDX using a default export.
 *
 * @param {{readonly [K in keyof MDXLayoutProps]: MDXLayoutProps[K]}} ${propsName}
 *   The [props](https://mdxjs.com/docs/using-mdx/#props) that have been passed to the MDX component.
 *   In addition, the MDX layout receives the \`children\` prop, which contains the rendered MDX content.
 */`

/**
 * @param {boolean} isAsync
 *   Whether or not the `_createMdxContent` should be async
 * @param {Scope} [scope]
 * @param {boolean} [hasImportSource]
 */
const createMdxContentStart = (isAsync, scope, hasImportSource) => `
/**
 * @internal
 *   **Do not use.** This function is generated by MDX for internal use.
 *
 * @param {{readonly [K in keyof MDXContentProps]: MDXContentProps[K]}} props
 *   The [props](https://mdxjs.com/docs/using-mdx/#props) that have been passed to the MDX component.
 * @returns {${isAsync ? 'Promise<JSX.Element>' : 'JSX.Element'}}
 *   A JSX element which represents the MDX content.
 */
${isAsync ? 'async ' : ''}function _createMdxContent(props) {
  /**
   * @internal
   *   **Do not use.** This variable is generated by MDX for internal use.
   */
  const _components = {${hasImportSource ? '\n    ..._provideComponents(),' : ''}
    ...props.components,
    /** The [props](https://mdxjs.com/docs/using-mdx/#props) that have been passed to the MDX component. */
    props${
      scope?.defined.map((name) => `,\n    /** {@link ${name}} */\n    ${name}`).join('') ?? ''
    }
  }
  _components
  return <_Fragment>`

const createMdxContentEnd = `
  </_Fragment>
}
`

const mdxContentStart = `
/**
 * Render the MDX contents.
 *
 * @param {{readonly [K in keyof MDXContentProps]: MDXContentProps[K]}} props
 *   The [props](https://mdxjs.com/docs/using-mdx/#props) that have been passed to the MDX component.
 * @returns {JSX.Element}
 *   A JSX element which represents the MDX content.
 */
export default function MDXContent(props) {
  return `

const mdxContentEnd = `
}

// @ts-ignore
/** @typedef {(void extends Props ? {} : Props) & {components?: {}}} MDXContentProps */
`

const jsxIndent = '\n    '

/**
 * A fallback to use if generating mapped content fails.
 *
 * @param {string} jsxImportSource
 *   The string to use for the JSX import source tag.
 */
const fallback = (jsxImportSource) =>
  jsPrefix(jsxImportSource) +
  createMdxContentStart(false) +
  createMdxContentEnd +
  mdxContentStart +
  mdxContentEnd

/**
 * @param {ExportDefaultDeclaration} node
 * @returns {string | undefined}
 */
function getPropsName(node) {
  const { declaration } = node
  const { type } = declaration

  if (
    type !== 'ArrowFunctionExpression' &&
    type !== 'FunctionDeclaration' &&
    type !== 'FunctionExpression'
  ) {
    return
  }

  if (declaration.params.length === 1) {
    const parameter = declaration.params[0]
    if (parameter.type === 'Identifier') {
      return parameter.name
    }
  }

  return 'props'
}

/** @type {Partial<Record<Nodes["type"], string>>} */
const mdastElementNodeNameMap = {
  blockquote: 'blockquote',
  break: 'br',
  delete: 'del',
  emphasis: 'em',
  html: 'html',
  image: 'img',
  imageReference: 'img',
  inlineCode: 'code',
  link: 'a',
  linkReference: 'a',
  listItem: 'li',
  paragraph: 'p',
  strong: 'strong',
  table: 'table',
  tableCell: 'td',
  tableRow: 'tr',
  thematicBreak: 'hr'
}

/**
 * Get the JSX node names for a given AST node.
 *
 * @param {Nodes} node
 * @returns {string}
 */
function getJsxNodeNameForMdast(node) {
  if (node.type === 'heading') {
    return `h${node.depth}`
  }

  if (node.type === 'list') {
    return node.ordered ? 'ol' : 'ul'
  }

  if (mdastElementNodeNameMap[node.type]) {
    return /** @type string */ (mdastElementNodeNameMap[node.type])
  }

  // JSX Fragment
  return ''
}

/**
 * @param {string} mdx
 * @param {Root} ast
 * @param {VirtualCodePluginObject[]} plugins
 * @param {boolean} checkMdx
 * @param {boolean} checkCodeBlocks
 * @param {string} jsxImportSource
 * @param {string | undefined} providerImportSource
 * @returns {TransformResult}
 */
export function getEmbeddedCodes(
  mdx,
  ast,
  plugins,
  checkMdx,
  checkCodeBlocks,
  jsxImportSource,
  providerImportSource
) {
  let hasAwait = false
  let esm = checkMdx ? '// @ts-check\n' : ''
  let jsx = ''
  let jsxVariables = ''

  /** @type {Node | undefined} */
  let layoutNode

  /** @type {MappedOutput[] | undefined} */
  let supplemental

  /**
   * The Volar mapping that maps all ESM syntax of the MDX file to the virtual JavaScript file.
   *
   * @type {SpanMapping[]}
   */
  const esmMappings = []

  /**
   * The Volar mapping that maps all JSX syntax of the MDX file to the virtual JavaScript file.
   *
   * @type {SpanMapping[]}
   */
  const jsxMappings = []

  /**
   * @type {SpanMapping[]}
   */
  const jsxVariablesMapping = []

  const visitors = createVisitors()

  for (const child of ast.children) {
    if (child.type !== 'mdxjsEsm') {
      continue
    }

    const estree = child.data?.estree

    if (estree) {
      walk(estree, {
        enter(node) {
          visitors.enter(node)

          if (
            node.type === 'ArrowFunctionExpression' ||
            node.type === 'FunctionDeclaration' ||
            node.type === 'FunctionExpression'
          ) {
            this.skip()
            visitors.exit(node)
          }
        },
        leave: visitors.exit
      })
    }
  }

  const programScope = visitors.scopes[0]

  esm += jsPrefix(jsxImportSource)
  if (providerImportSource) {
    esm += `import { useMDXComponents as _provideComponents } from ${JSON.stringify(providerImportSource)}\n`
  }

  /**
   * Process exports of an MDX ESM node.
   *
   * @param {MdxjsEsm} node
   *   The MDX ESM node to process.
   * @returns {undefined}
   */
  function processExports(node) {
    const start = node.position?.start?.offset
    const end = node.position?.end?.offset

    if (start === undefined || end === undefined) {
      return
    }

    const body = node.data?.estree?.body

    if (!body?.length) {
      esm = addOffset(esmMappings, mdx, esm, start, end, true)
      return
    }

    bodyLoop: for (const child of body) {
      if (child.type === 'ExportDefaultDeclaration') {
        const propsName = getPropsName(child)
        layoutNode = child
        if (propsName) {
          esm += layoutJsDoc(propsName)
        }

        esm = addOffset(
          esmMappings,
          mdx,
          `${esm}\nconst MDXLayout = `,
          child.declaration.start,
          child.end,
          true
        )
        continue
      }

      if (child.type === 'ExportNamedDeclaration' && child.source) {
        const { specifiers } = child
        for (let index = 0; index < specifiers.length; index += 1) {
          const specifier = specifiers[index]
          if (
            specifier.local.type === 'Identifier'
              ? specifier.local.name === 'default'
              : specifier.local.value === 'default'
          ) {
            layoutNode = specifier
            esm = addOffset(esmMappings, mdx, esm, start, specifier.start)
            const nextPosition =
              index === specifiers.length - 1 ? specifier.end : mdx.indexOf(',', specifier.end) + 1
            esm = addOffset(esmMappings, mdx, esm, nextPosition, end, true)
            esm += '\nimport {'
            esm +=
              specifier.exported.type === 'Identifier'
                ? specifier.exported.name
                : JSON.stringify(specifier.exported.value)
            esm += ' as MDXLayout} from '
            const sourceLength = child.source.end - child.source.start
            esmMappings.unshift([esm.length, sourceLength, child.source.start, sourceLength, 0, 0])
            esm += child.source.raw
            continue bodyLoop
          }
        }
      }

      esm = addOffset(esmMappings, mdx, esm, child.start, child.end, true)
    }

    esm += '\n'
  }

  /**
   * @param {Program} program
   * @param {number} lastIndex
   * @returns {number}
   */
  function processJsxExpression(program, lastIndex) {
    /** @type {Map<Node, Scope | undefined>} */
    const localScopes = new Map()

    /** @type {Map<Node, Node | null>} */
    const parents = new Map()
    let newIndex = lastIndex
    let functionNesting = 0

    /**
     * @param {JSXClosingElement | JSXOpeningElement} node
     * @returns {undefined}
     */
    function processJsxTag(node) {
      const { name } = node

      if (name.type !== 'JSXIdentifier') {
        return
      }

      if (!isInjectableEstree(name, localScopes, parents)) {
        return
      }

      jsx = `${addOffset(jsxMappings, mdx, jsx, newIndex, name.start)}_components.`
      if (node.name && node.type === 'JSXOpeningElement') {
        jsxVariables = `${addOffset(
          jsxVariablesMapping,
          mdx,
          `${jsxVariables}// @ts-ignore\n`,
          name.start,
          name.end
        )}\n`
      }

      newIndex = name.start
    }

    walk(program, {
      enter(node, parent) {
        if (node.type === 'Program') {
          return
        }

        visitors.enter(node)
        localScopes.set(node, visitors.scopes.at(-1))
        parents.set(node, parent)
      },
      leave(node) {
        if (node.type === 'Program') {
          return
        }

        visitors.exit(node)
      }
    })

    walk(program, {
      enter(node) {
        switch (node.type) {
          case 'JSXElement':
            processJsxTag(node.openingElement)
            break

          case 'ArrowFunctionExpression':
          case 'FunctionDeclaration':
          case 'FunctionExpression':
            functionNesting += 1
            break

          case 'AwaitExpression':
            if (!functionNesting) {
              hasAwait = true
            }

            break

          case 'ForOfStatement':
            if (!functionNesting) {
              hasAwait ||= node.await
            }

            break

          default:
        }
      },

      leave(node) {
        switch (node.type) {
          case 'ArrowFunctionExpression':
          case 'FunctionDeclaration':
          case 'FunctionExpression':
            functionNesting -= 1
            break

          case 'JSXElement': {
            const { closingElement } = node

            if (closingElement) {
              processJsxTag(closingElement)
            }

            break
          }

          default:
        }
      }
    })

    return newIndex
  }

  visit(
    ast,
    (node) => {
      const start = node.position?.start?.offset
      let end = node.position?.end?.offset

      if (start === undefined || end === undefined) {
        return
      }

      for (const plugin of plugins) {
        plugin.visit?.(node)
      }

      switch (node.type) {
        case 'code':
          jsx += jsxIndent
          jsx += '<pre>'
          jsx += jsxIndent
          jsx += '<code>'
          if (checkCodeBlocks) {
            const output = processCodeBlock(node, mdx)
            if (output) {
              supplemental ||= []
              supplemental.push(output)
            }
          }
          break

        case 'mdxjsEsm':
          processExports(node)
          break

        case 'mdxJsxFlowElement':
        case 'mdxJsxTextElement': {
          if (node.children.length > 0) {
            end = mdx.lastIndexOf('>', getNodeStartOffset(node.children[0]) - 1) + 1
          }

          let lastIndex = start + 1
          jsx = addOffset(jsxMappings, mdx, jsx + jsxIndent, start, lastIndex)
          if (isInjectableComponent(node.name, programScope)) {
            jsx += '_components.'
            if (node.name) {
              jsxVariables += '// @ts-ignore\n'
              jsxVariables = addOffset(
                jsxVariablesMapping,
                mdx,
                jsxVariables,
                lastIndex,
                lastIndex + node.name.length
              )
              jsxVariables += '\n'
            }
          }

          if (node.name) {
            jsx = addOffset(jsxMappings, mdx, jsx, lastIndex, lastIndex + node.name.length)
            lastIndex += node.name.length
          }

          for (const attribute of node.attributes) {
            if (typeof attribute.value !== 'object') {
              continue
            }

            const program = attribute.value?.data?.estree

            if (program) {
              lastIndex = processJsxExpression(program, lastIndex)
            }
          }

          jsx = addOffset(jsxMappings, mdx, jsx, lastIndex, end)
          break
        }

        case 'mdxFlowExpression':
        case 'mdxTextExpression': {
          const program = node.data?.estree
          jsx += jsxIndent

          if (program?.body.length) {
            const newIndex = processJsxExpression(program, start)
            jsx = addOffset(jsxMappings, mdx, jsx, newIndex, end)
          } else {
            jsx = addOffset(jsxMappings, mdx, jsx, start, start + 1)
            jsx = addOffset(jsxMappings, mdx, jsx, end - 1, end)
            esm = addOffset(esmMappings, mdx, esm, start + 1, end - 1)
            esm += '\n'
          }

          break
        }

        case 'root':
        case 'toml':
        case 'yaml':
          break

        case 'text':
          jsx += jsxIndent
          jsx += "{''}"
          break

        default:
          jsx += jsxIndent
          jsx += '<'
          jsx += getJsxNodeNameForMdast(node)
          jsx += '>'
          break
      }
    },
    (node) => {
      switch (node.type) {
        case 'code':
          jsx += jsxIndent
          jsx += '</code>'
          jsx += jsxIndent
          jsx += '</pre>'
          break
        case 'mdxJsxFlowElement':
        case 'mdxJsxTextElement': {
          const child = node.children?.at(-1)

          if (child) {
            const start = mdx.indexOf('<', getNodeEndOffset(child) - 1)
            const end = getNodeEndOffset(node)

            if (isInjectableComponent(node.name, programScope)) {
              const closingStart = start + 2
              jsx = addOffset(jsxMappings, mdx, jsx + jsxIndent, start, closingStart)
              jsx += '_components.'
              jsx = addOffset(jsxMappings, mdx, jsx, closingStart, end)
            } else {
              jsx = addOffset(jsxMappings, mdx, jsx + jsxIndent, start, end)
            }
          }

          break
        }

        case 'mdxTextExpression':
        case 'mdxjsEsm':
        case 'mdxFlowExpression':
        case 'root':
        case 'text':
        case 'toml':
        case 'yaml':
          break

        default:
          jsx += jsxIndent
          jsx += '</'
          jsx += getJsxNodeNameForMdast(node)
          jsx += '>'
          break
      }
    }
  )

  for (const plugin of plugins) {
    esm += '\n'
    const [pluginCode, pluginMappings] = plugin.finalize()
    padOffsets(pluginMappings, esm.length)
    esmMappings.push(...pluginMappings)
    esm += pluginCode
    esm += '\n'
  }

  esm += createMdxContentStart(hasAwait, programScope, Boolean(providerImportSource))

  padOffsets(jsxMappings, esm.length)
  esm += jsx + createMdxContentEnd + mdxContentStart
  esm += '<'
  if (layoutNode) {
    esmMappings.push([esm.length, 9, layoutNode.start, layoutNode.end - layoutNode.start, 1, 0])
    esm += 'MDXLayout {...props}'
  } else {
    esm += '_Fragment'
  }
  esm += '>\n'
  esm += '    <_createMdxContent {...props} />\n'
  esm += `  </${layoutNode ? 'MDXLayout' : '_Fragment'}>`
  esm += mdxContentEnd

  padOffsets(jsxVariablesMapping, esm.length)
  esm += jsxVariables

  return {
    text: esm,
    extension: '.jsx',
    mappings: [...esmMappings, ...jsxMappings, ...jsxVariablesMapping],
    supplemental
  }
}

/**
 * Transform MDX content into mapped TypeScript content.
 *
 * @param {TransformParams} params
 *   The transform parameters as sent by TypeScript.
 * @returns {Promise<TransformResult>}
 *   The transform result that TypeScript expects.
 */
export async function transform(params) {
  const project = projects.get(params.projectHandle)
  const jsxImportSource = project?.compilerOptions?.jsxImportSource ?? 'react'

  try {
    const options = project?.options
    const processor = unified().use(remarkParse)
    if (!hasExtension(params.fileName, getMarkdownExtensions(options?.markdownExtensions))) {
      processor.use(remarkMdx)
    }
    const plugins = await resolvePlugins(processor, options)
    const root = processor.parse(params.content)
    return getEmbeddedCodes(
      params.content,
      root,
      plugins,
      Boolean(options?.checkMdx),
      Boolean(options?.checkCodeBlocks),
      jsxImportSource,
      resolveProviderImportSource(
        params.fileName,
        project?.configFileName,
        options?.providerImportSource
      )
    )
  } catch (error) {
    return {
      diagnostics: [toDiagnostic(error)],
      mappings: [],
      extension: '.jsx',
      text: fallback(jsxImportSource)
    }
  }
}
